---
- name: Install MySQL
  action: apt pkg={{item}} state=latest install_recommends=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  tags: mysql

- name: Start MySQL daemon if not running
  script: start_mysql_if_needed.sh
  tags: mysql

- name: Update MySQL root password for all root account
  mysql_user: name=root password={{mysql_root_password}}
  tags: mysql

- name: Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mysql

- name: Create MySQL db {{db_name}}
  mysql_db: name={{db_name}} encoding=utf8 collation=utf8_general_ci
  tags: mysql

- name: Update db username and password for {{db_name}}
  mysql_user: name={{db_user}} host={{item}} password={{db_password}} priv={{db_name}}.*:ALL state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql
